image: maven:3-jdk-11

stages:
  - deploy

deploy-devlop-branch:
  stage: deploy
  only:
    refs:
      - master
  image: ruby:2.6
  script:
    - echo "Heroku Depoloy!"
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=shop-store-arek123 --api-key=d4dd94db-5579-45a0-963d-db6ed57dc8c5
